import React,{useState} from "react";
import {useNavigate} from "react-router-dom";
import {login} from "../api";
import {useApp} from "../context/AppContext";

export default function Login(){
 const [role,setRole]=useState("customer"),[email,setEmail]=useState("customer@metriq.local"),[password,setPassword]=useState("customer123"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const {signIn,dark,toggleTheme}=useApp(),nav=useNavigate();
 const changeRole=r=>{setRole(r);setError("");if(r==="customer"){setEmail("customer@metriq.local");setPassword("customer123")}else{setEmail("master@metriq.local");setPassword("master123")}};
 const submit=async e=>{e.preventDefault();setLoading(true);setError("");try{const data=await login(email,password,role);signIn(data);nav(role==="master"?"/dashboard":"/scan")}catch(err){setError(err.message)}finally{setLoading(false)}};
 return <div className="min-h-screen overflow-hidden bg-[#fff9f4] dark:bg-[#101012]"><div className="absolute inset-0 grid-bg opacity-70"/><div className="relative grid min-h-screen lg:grid-cols-[1.05fr_.95fr]">
  <div className="hidden items-center justify-center p-12 lg:flex"><div className="max-w-xl"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-[#7f1d3a] to-[#ff5a5f] text-xl font-black text-white shadow-glow">M</div><div><div className="font-display text-xl font-bold dark:text-white">METRIQ</div><div className="text-[9px] uppercase tracking-[.25em] text-[#7f1d3a] dark:text-[#ffb547]">Compliance AI</div></div></div><h1 className="mt-10 font-display text-6xl font-black leading-[.98] dark:text-white">Inspect the package.<br/><span className="text-[#7f1d3a] dark:text-[#ffb547]">Know the label.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-[#75666a] dark:text-[#bdb2b5]">A visual Legal Metrology workspace for customers and master inspectors, powered by OCR and an explainable rules engine.</p><div className="mt-8 flex gap-3 text-xs font-bold"><span className="rounded-full bg-[#19c37d]/10 px-3 py-2 text-[#19c37d]">● OCR READY</span><span className="rounded-full bg-[#ffb547]/15 px-3 py-2 text-[#9a6200]">RULE-AWARE</span><span className="rounded-full bg-[#7f1d3a]/10 px-3 py-2 text-[#7f1d3a] dark:text-[#ffb547]">3D SCANNER</span></div></div></div>
  <div className="flex items-center justify-center p-5 sm:p-10"><div className="glass w-full max-w-md rounded-[34px] p-7 shadow-2xl sm:p-9"><div className="flex justify-between"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-[#7f1d3a] dark:text-[#ffb547]">Secure workspace</div><h2 className="mt-2 font-display text-3xl font-black">Welcome back</h2></div><button onClick={toggleTheme} className="h-10 w-10 rounded-xl border dark:border-white/10">{dark?"☀":"☾"}</button></div>
   <div className="mt-7 grid grid-cols-2 gap-2 rounded-2xl bg-black/5 p-1 dark:bg-white/5">{[["customer","Customer"],["master","Master"]].map(([r,label])=><button type="button" key={r} onClick={()=>changeRole(r)} className={`rounded-xl py-3 text-sm font-bold transition ${role===r?"bg-[#7f1d3a] text-white shadow-lg":"text-[#75666a] dark:text-[#bdb2b5]"}`}>{r==="customer"?"👤":"🛡️"} {label}</button>)}</div>
   <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-bold uppercase tracking-wider">Email<input value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-2xl border border-black/10 bg-white/70 px-4 py-3 text-sm outline-none focus:border-[#ff5a5f] dark:border-white/10 dark:bg-white/5" type="email" required/></label><label className="block text-xs font-bold uppercase tracking-wider">Password<input value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-2xl border border-black/10 bg-white/70 px-4 py-3 text-sm outline-none focus:border-[#ff5a5f] dark:border-white/10 dark:bg-white/5" type="password" required/></label>{error&&<div className="rounded-2xl bg-red-500/10 p-3 text-xs font-semibold text-red-600">{error}</div>}<button disabled={loading} className="w-full rounded-2xl bg-gradient-to-r from-[#7f1d3a] to-[#ff5a5f] py-4 font-bold text-white shadow-lg disabled:opacity-50">{loading?"Signing in…":`Continue as ${role==="master"?"Master":"Customer"} →`}</button></form>
   <div className="mt-5 rounded-2xl bg-[#ffb547]/10 p-3 text-[10px] leading-5 text-[#77551b] dark:text-[#d9b76c]"><b>Demo accounts</b><br/>Customer: customer@metriq.local / customer123<br/>Master: master@metriq.local / master123</div>
  </div></div>
 </div></div>
}