import React,{useEffect,useRef,useState} from "react";
import {useNavigate} from "react-router-dom";
import Scanner3D from "../components/Scanner3D";
import {scanProduct} from "../api";
import {useApp} from "../context/AppContext";

const stages=["Initializing scanner","Detecting package","Reading label","Extracting declarations","Checking mandatory information","Generating report"];
export default function Scan(){
 const [file,setFile]=useState(null),[image,setImage]=useState(null),[scanning,setScanning]=useState(false),[progress,setProgress]=useState(0),[stage,setStage]=useState(0),[error,setError]=useState("");
 const [camera,setCamera]=useState(false),[stream,setStream]=useState(null);
 const videoRef=useRef(null),canvasRef=useRef(null),nav=useNavigate(),{addScan,token}=useApp();
 useEffect(()=>{if(!scanning)return;const t=setInterval(()=>setProgress(p=>{const n=Math.min(92,p+6);setStage(Math.min(stages.length-1,Math.floor(n/(100/stages.length))));return n}),150);return()=>clearInterval(t)},[scanning]);
 useEffect(()=>()=>{stream?.getTracks().forEach(t=>t.stop())},[stream]);
 const choose=f=>{if(!f||!f.type.startsWith("image/")){setError("Choose a PNG, JPG, JPEG or WEBP image.");return}setFile(f);setImage(URL.createObjectURL(f));setError("")};
 const openCamera=async()=>{try{setError("");if(!navigator.mediaDevices?.getUserMedia)throw new Error();const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});setStream(s);setCamera(true);setTimeout(()=>{if(videoRef.current){videoRef.current.srcObject=s;videoRef.current.play().catch(()=>{})}},50)}catch{setError("Camera access failed. Use HTTPS/localhost and allow camera permission.")}};
 const closeCamera=()=>{stream?.getTracks().forEach(t=>t.stop());setStream(null);setCamera(false)};
 const capture=()=>{const v=videoRef.current,c=canvasRef.current;if(!v||!c)return;c.width=v.videoWidth||1280;c.height=v.videoHeight||720;c.getContext("2d").drawImage(v,0,0,c.width,c.height);c.toBlob(b=>{if(!b)return;choose(new File([b],"camera-product.jpg",{type:"image/jpeg"}));closeCamera()},"image/jpeg",.92)};
 const run=async()=>{if(!file)return;setScanning(true);setProgress(5);setError("");try{const r=await scanProduct(file,token);setProgress(100);addScan(r);setTimeout(()=>nav("/results"),500)}catch(e){setError(e.message||"Scan failed");setScanning(false);setProgress(0)}};
 return <div className="mx-auto max-w-7xl space-y-6"><div><div className="text-xs font-bold uppercase tracking-[.2em] text-[#7f1d3a] dark:text-[#ffb547]">Live camera + OCR + rules</div><h1 className="mt-1 font-display text-3xl font-black">Product Scanner</h1><p className="mt-2 text-sm text-[#75666a] dark:text-[#bdb2b5]">Point your camera at a packaged commodity or upload a label.</p></div>
 <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="glass rounded-[32px] p-4 sm:p-7"><Scanner3D image={image} scanning={scanning}/>{scanning&&<div className="mx-auto max-w-md rounded-2xl bg-[#7f1d3a]/7 p-4 dark:bg-white/5"><div className="flex justify-between text-xs font-bold"><span>{stages[stage]}</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-black/10 dark:bg-white/10"><div style={{width:`${progress}%`}} className="h-full bg-gradient-to-r from-[#ffb547] to-[#ff5a5f] transition-all"/></div></div>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={openCamera} disabled={scanning} className="rounded-2xl bg-gradient-to-r from-[#7f1d3a] to-[#ff5a5f] px-5 py-4 text-left font-bold text-white transition hover:-translate-y-1 disabled:opacity-40">📷 Direct Camera Scan<div className="mt-1 pl-8 text-[10px] font-normal text-white/70">Open camera and capture label</div></button><label className="cursor-pointer rounded-2xl border border-[#7f1d3a]/15 bg-white/70 px-5 py-4 text-left font-bold transition hover:-translate-y-1 dark:border-white/10 dark:bg-white/5">🖼️ Upload Label<div className="mt-1 pl-8 text-[10px] font-normal text-[#75666a] dark:text-[#bdb2b5]">PNG, JPG, WEBP</div><input hidden type="file" accept="image/*" onChange={e=>choose(e.target.files[0])}/></label></div></div>
 <div className="glass rounded-[32px] p-6"><div className="rounded-3xl border-2 border-dashed border-[#7f1d3a]/15 p-5 text-center dark:border-white/10"><div className="text-4xl">{image?"🔎":"📦"}</div><h2 className="mt-3 font-display font-bold">{image?"Package ready for inspection":"Ready to inspect"}</h2>{image&&<div className="mt-4 h-36 overflow-hidden rounded-2xl bg-white dark:bg-white/5"><img src={image} className="h-full w-full object-contain" alt="Selected product"/></div>}<p className="mt-3 text-xs text-[#75666a] dark:text-[#bdb2b5]">Use bright, even lighting and keep the label inside the frame.</p></div>{error&&<div className="mt-4 rounded-2xl bg-red-500/10 p-3 text-xs font-semibold text-red-600">{error}</div>}<button disabled={!file||scanning} onClick={run} className="mt-5 w-full rounded-xl bg-gradient-to-r from-[#7f1d3a] to-[#ff5a5f] py-3 font-bold text-white disabled:opacity-40">{scanning?"Analyzing with OCR…":"Start Real Compliance Scan →"}</button></div></div>
 <canvas ref={canvasRef} className="hidden"/>
 {camera&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/85 p-4 backdrop-blur-md"><div className="w-full max-w-4xl overflow-hidden rounded-[32px] border border-white/15 bg-[#151214] shadow-2xl"><div className="flex items-center justify-between p-4 text-white"><div><div className="text-[10px] uppercase tracking-[.2em] text-[#ffb547]">Direct camera scan</div><div className="font-display font-bold">Align the package label</div></div><button onClick={closeCamera} className="rounded-xl bg-white/10 px-3 py-2">✕</button></div><div className="relative aspect-video bg-black"><video ref={videoRef} playsInline muted className="h-full w-full object-cover"/><div className="pointer-events-none absolute inset-[10%] rounded-3xl border-2 border-[#ffb547] shadow-[0_0_45px_rgba(255,181,71,.18)]"><div className="absolute left-1/2 top-1/2 h-px w-full -translate-x-1/2 bg-[#ff5a5f] shadow-[0_0_18px_4px_#ff5a5f]"/><span className="absolute -top-7 left-0 text-[9px] font-bold uppercase tracking-[.2em] text-[#ffb547]">SCAN AREA</span></div></div><div className="flex justify-center gap-4 p-5"><button onClick={capture} className="grid h-16 w-16 place-items-center rounded-full border-4 border-white bg-[#ff5a5f] text-2xl shadow-[0_0_35px_rgba(255,90,95,.45)] hover:scale-105">●</button><button onClick={closeCamera} className="rounded-xl bg-white/10 px-5 py-3 text-sm font-bold text-white">Cancel</button></div></div></div>}
 </div>
}